import '@/assets/scss/main.scss'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { AntdRegistry } from '@ant-design/nextjs-registry';
import {ReduxProvider} from "@/stores/provider";

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
    weight: ['300','400','500', '700'], // можно перечислят
    subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Интерент магазин DEMO',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <ReduxProvider>
              <AntdRegistry>{children}</AntdRegistry>
          </ReduxProvider>
      </body>
    </html>
  )
}
